### ISSUE TITLE
Make data available for download via GIS portal

### ISSUE THREAD

**Issue by smoran3** [rbeatty1/RTPS#72] opened 2019-03-21 15:43 UTC
https://docs.google.com/spreadsheets/d/1cn3EZxMqeQAbt0eRMhi3QJX5MPoRs7DMLkfiWfj1k0E/edit?usp=sharing

I pulled together the data that I want to make available via the GIS portal (once the website is live). I also added some metadata. Let me know if there is additional information I need to provide.

I only want to make data downloadable for one of the 4 maps. The rest are a little too confusing when taken out of context and probably have limited use outside of the webmap. Maybe the landing page for Surface Transit Reliability can have an extra link next to "Learn More" and "Explore" that says "Download." It should probably also be linked inside the Reliability page.

**Comment by rbeatty1** [comment] 2019-03-21 15:51
Duplicate of #67. Close #72

**Closed by rbeatty1** 2019-03-21 15:51 UTC
